---
- name: Remove iptables
  community.general.pacman:
    name: iptables
    state: absent
    force: yes
  become: yes
  when: ansible_os_family == 'Archlinux'

- name: Install lxd
  ansible.builtin.package:
    name: lxd
    state: present
  become: yes
