---
- name: Copy client certificate to the server
  ansible.builtin.copy:
    content: "{{ incus_client_cert.certificate }}"
    dest: ~/incus_client_certificates/{{ ansible_hostname }}_{{ incus_client_user }}.crt
    mode: 0600
  delegate_to: "{{ incus_client_remote }}"
  register: incus_client_copy_cert

- name: Add new client certificate in incus  # noqa no-handler
  ansible.builtin.command:
    cmd: incus config trust add-certificate {{ ansible_hostname }}_{{ incus_client_user }}.crt
    chdir: ~/incus_client_certificates
  delegate_to: "{{ incus_client_remote }}"
  changed_when: true
  when: incus_client_copy_cert.changed

- name: Copy server certificate to the client
  ansible.builtin.copy:
    content: "{{
      (
        (
          incus_client_server_info.results |
          selectattr('item', 'equalto', incus_client_remote)
        ).0.stdout |
        from_yaml
      ).environment.certificate }}"
    dest: "~/.config/incus/servercerts/{{ incus_client_remote }}.crt"
    mode: 0600
  become: yes
  become_user: "{{ incus_client_user }}"
