---
- name: Converge
  hosts: lxd_client
  tasks:
    - name: "Import lxd_client"
      ansible.builtin.import_role:
        name: "gliech.lxd_client"
      vars:
        lxd_client_remotes: "{{ groups.lxd_server }}"
