---
- name: Converge
  hosts: incus_client
  tasks:
    - name: "Import incus_client"
      ansible.builtin.import_role:
        name: "gliech.incus_client"
      vars:
        incus_client_remotes: "{{ groups.incus_server }}"
