---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/requirements.yml
    role-file: molecule/default/requirements.yml
driver:
  name: podman
platforms:
  - name: mol-incus-host
    image: gliech/docker-archlinux-ansible:branch-master
    groups:
      - incus_server
    pre_build_image: true
    privileged: true
    exposed_ports:
      - 8512/tcp
    published_ports:
      - 0.0.0.0:8512:8512/tcp
    port_bindings:
      8443: 8443
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: mol-incus-user
    image: gliech/docker-archlinux-ansible:branch-master
    groups:
      - incus_client
    pre_build_image: true
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      interpreter_python: auto_silent
verifier:
  name: ansible
scenario:
  check_sequence:
    - dependency
    - create
    - prepare
    - converge
    - check
  destroy_sequence:
    - dependency
    - destroy
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
