---
- name: Verify
  hosts: lxd_client
  gather_facts: false
  tasks:
    - name: Get facts from localhost
      ansible.builtin.setup:
      register: local_vars
      delegate_to: localhost

    - name: Replace server ip to work around docker networking
      ansible.builtin.replace:
        path: ~/.config/lxc/config.yml
        regexp: (?<=https://)mol-lxc-host
        replace: "{{ local_vars.ansible_facts.ansible_default_ipv4.address }}"

    - name: Read container list
      ansible.builtin.command: lxc info
      register: server_info
      changed_when: no

    - name: Verify lxc interacts with the remote server
      ansible.builtin.assert:
        that: (server_info.stdout | from_yaml).environment.server_name == 'mol-lxc-host'
        quiet: true
